[tool.poetry]
name = "moodle-quiz-archive-worker"
version = "1.1.2"
description = "Quiz archiver service to work in conjunction with the Moodle plugin 'quiz_archiver'"
authors = ["Niels Gandraß <niels@gandrass.de>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"
playwright = "^1.34.0"
requests = "^2.31.0"
waitress = "^2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
