blank_issues_enabled: false
contact_links:
  - name: Open a New Issue
    url: https://github.com/ngandrass/moodle-quiz_archiver/issues
    about: Please create all issues in the moodle quiz archiver plugin repository. Use the link on the right to get there.
  - name: Read the Documentation
    url: https://github.com/ngandrass/moodle-quiz-archive-worker/blob/master/README.md
    about: Have you already tried to find an answer to your question or problem in the docs?
