name: Python tests

on:
  push:
    branches: [ "master", "develop", "ci-test" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'poetry'

      - name: Install Python dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --with dev

      - name: Initialize playwright
        run: |
          poetry run playwright install chromium

      - name: Test with pytest
        run: |
          poetry run pytest
